# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recipe_pb2 as recipe__pb2


class RecipeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRecipe = channel.unary_unary(
        '/userpb.Recipe/GetRecipe',
        request_serializer=recipe__pb2.RecipeRequest.SerializeToString,
        response_deserializer=recipe__pb2.RecipeResponse.FromString,
        )


class RecipeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRecipe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecipeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRecipe': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecipe,
          request_deserializer=recipe__pb2.RecipeRequest.FromString,
          response_serializer=recipe__pb2.RecipeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'userpb.Recipe', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
