# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recipe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recipe.proto',
  package='userpb',
  syntax='proto3',
  serialized_pb=_b('\n\x0crecipe.proto\x12\x06userpb\"\x1e\n\rRecipeRequest\x12\r\n\x05title\x18\x01 \x01(\t\"4\n\x0eRecipeResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2F\n\x06Recipe\x12<\n\tGetRecipe\x12\x15.userpb.RecipeRequest\x1a\x16.userpb.RecipeResponse\"\x00\x62\x06proto3')
)




_RECIPEREQUEST = _descriptor.Descriptor(
  name='RecipeRequest',
  full_name='userpb.RecipeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='userpb.RecipeRequest.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=54,
)


_RECIPERESPONSE = _descriptor.Descriptor(
  name='RecipeResponse',
  full_name='userpb.RecipeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='userpb.RecipeResponse.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='userpb.RecipeResponse.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['RecipeRequest'] = _RECIPEREQUEST
DESCRIPTOR.message_types_by_name['RecipeResponse'] = _RECIPERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecipeRequest = _reflection.GeneratedProtocolMessageType('RecipeRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECIPEREQUEST,
  __module__ = 'recipe_pb2'
  # @@protoc_insertion_point(class_scope:userpb.RecipeRequest)
  ))
_sym_db.RegisterMessage(RecipeRequest)

RecipeResponse = _reflection.GeneratedProtocolMessageType('RecipeResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECIPERESPONSE,
  __module__ = 'recipe_pb2'
  # @@protoc_insertion_point(class_scope:userpb.RecipeResponse)
  ))
_sym_db.RegisterMessage(RecipeResponse)



_RECIPE = _descriptor.ServiceDescriptor(
  name='Recipe',
  full_name='userpb.Recipe',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=110,
  serialized_end=180,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecipe',
    full_name='userpb.Recipe.GetRecipe',
    index=0,
    containing_service=None,
    input_type=_RECIPEREQUEST,
    output_type=_RECIPERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECIPE)

DESCRIPTOR.services_by_name['Recipe'] = _RECIPE

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class RecipeStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetRecipe = channel.unary_unary(
          '/userpb.Recipe/GetRecipe',
          request_serializer=RecipeRequest.SerializeToString,
          response_deserializer=RecipeResponse.FromString,
          )


  class RecipeServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetRecipe(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_RecipeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetRecipe': grpc.unary_unary_rpc_method_handler(
            servicer.GetRecipe,
            request_deserializer=RecipeRequest.FromString,
            response_serializer=RecipeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'userpb.Recipe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaRecipeServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetRecipe(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaRecipeStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def GetRecipe(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetRecipe.future = None


  def beta_create_Recipe_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('userpb.Recipe', 'GetRecipe'): RecipeRequest.FromString,
    }
    response_serializers = {
      ('userpb.Recipe', 'GetRecipe'): RecipeResponse.SerializeToString,
    }
    method_implementations = {
      ('userpb.Recipe', 'GetRecipe'): face_utilities.unary_unary_inline(servicer.GetRecipe),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Recipe_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('userpb.Recipe', 'GetRecipe'): RecipeRequest.SerializeToString,
    }
    response_deserializers = {
      ('userpb.Recipe', 'GetRecipe'): RecipeResponse.FromString,
    }
    cardinalities = {
      'GetRecipe': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'userpb.Recipe', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
